name: CI

on: [push, pull_request]

jobs:
  check:
    name: Check
    runs-on: ubuntu-latest
    # Execute the checks inside the container instead the VM.
    container: golangci/golangci-lint:v1.60.3-alpine
    steps:
      - uses: actions/checkout@v4
      - run: |
          # We need this go flag because it started to error after golangci-lint is using Go 1.21.
          # TODO(slok): Remove it on next (>1.54.2) golangci-lint upgrade to check if this problem has gone.
          export GOFLAGS="-buildvcs=false"
          golangci-lint run

  unit-test:
    name: Unit test
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-go@v5
        with:
          go-version-file: go.mod
          cache: false
      - run: make test

  integration-test:
    name: Integration test
    runs-on: ubuntu-latest
    needs: [check, unit-test]
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-go@v5
        with:
          go-version-file: go.mod
          cache: false
      - run: make integration-test
